import React, { useMemo, useState } from 'react';
import { Solve, StatConfig, StatType, Penalty, PBVisualType, AppTheme, TimePrecision, Language } from '../../types';
import { 
	formatTime, 
	formatPercent,
	getSolveTime,
	getStatLabel,
	getCurrentStatValue,
	getBestStatValue,
	getThemeTextColorClass,
	DNF_VALUE,
	APP_VERSION
} from '../../utils';
import { t } from '../../translations';

interface StatsPanelProps {
  config: StatConfig[];
  solves: Solve[]; // Sorted Oldest -> Newest
  theme: AppTheme;
  pbVisuals: PBVisualType;
  precision: TimePrecision;
  language?: Language;
}

type StatsPanelData = {
	config: StatConfig[];
	solves: Solve[];
	theme: AppTheme;
	pbVisuals: PBVisualType;
	precision: TimePrecision;
	language?: Language;
}

type StatValues = {
	current: number | null;
	best: number | null;
	bestWindow: Solve[] | null;
};

const getValues = (stat: StatConfig, history: Solve[]): StatValues => {
	const current = getCurrentStatValue(stat, history);
	const { best, bestWindow } = getBestStatValue(stat, history);
	return { current, best, bestWindow };
};

const StatsPanel: React.FC<StatsPanelProps> = (dta: StatsPanelData) => {
	const { config, solves, theme, pbVisuals, precision, language } = dta;
	const [copyFeedback, setCopyFeedback] = useState<string | null>(null);

	// Calculates the worst time needed on the next solve to beat the current PB
	const getRequiredTime = (stat: StatConfig, history: Solve[], currentPB: number | null): number | null | 'IMPOSSIBLE' | 'ANY' => {
		if (!currentPB || currentPB === DNF_VALUE) return null;
		const N = stat.size;
      
		// Need at least N-1 prior solves to calculate next average
		if (history.length < N - 1) return null; 

		// Get last N-1 solves (Recent history, since input is Chronological)
		const context = history.slice(history.length - (N - 1));
		const times = context.map(s => getSolveTime(s));

		// SINGLE
		if (stat.type === StatType.SINGLE) 
			return currentPB; 
      

		// MEAN
		if (stat.type === StatType.MEAN) {
			if (times.some(t => t === null)) return null; // If recent history has DNF, can't calculate mean
			const sum = (times as number[]).reduce((a, b) => a + b, 0);
			// (Sum + X) / N < PB  => X < PB*N - Sum
			const req = (currentPB * N) - sum;
			return req > 0 ? req : 'IMPOSSIBLE'; 
		}

		// AVERAGE
		if (stat.type === StatType.AVERAGE) {
			// Treat DNF as Infinity for sorting
			const numTimes = times.map(t => t === null ? Infinity : t).sort((a, b) => a - b);
          
			// Only support standard 5% trim (1 for 5, 1 for 12)
			const numDiscard = Math.ceil(N * 0.05);
			if (numDiscard !== 1) return null; 

			// Check max DNF count in history. If > 1, next solve (worst case) will result in DNF.
			const dnfCount = numTimes.filter(t => t === Infinity).length;
			if (dnfCount > 1) return 'IMPOSSIBLE';

			// 1. Check if ANY (Worst case works)
			// Worst case: Next solve is Infinity (DNF).
			// If 0 DNFs in history, adding 1 DNF is fine (it gets trimmed).
			// Sum becomes sum of all current excluding min.
			if (dnfCount === 0) {
				const sumWorstCase = numTimes.slice(1).reduce((a, b) => a + b, 0);
				const avgWorstCase = sumWorstCase / (N - 2);
				if (avgWorstCase < currentPB) return 'ANY';
			}

			// 2. Check IMPOSSIBLE (Best case fails)
			// Best case: Next solve is 0.
			// If history has any DNF, 0 and DNF are trimmed.
			// If history has NO DNF, 0 and max(History) are trimmed.
          
			// If history has a DNF, max is Infinity.
			const sumBestCase = numTimes.slice(0, N - 2).reduce((a, b) => a + (b === Infinity ? 0 : b), 0);
          
			// If remaining sum has Infinity?
			if (numTimes.slice(0, N - 2).includes(Infinity)) return 'IMPOSSIBLE';
          
			const avgBestCase = sumBestCase / (N - 2);
			if (avgBestCase >= currentPB) return 'IMPOSSIBLE';

			// 3. Calculate Target
			// We need X such that it is a counting solve (not min, not max).
			// Sum = Sum(middle of H) + X.
			// Middle of H = H excluding min and max.
			const sumInnerHistory = numTimes.slice(1, N - 2).reduce((a, b) => a + b, 0);
          
			const targetTotal = currentPB * (N - 2);
			const result = targetTotal - sumInnerHistory;
          
			return result;
		}

		return null;
	};

	const handleExport = (e: React.MouseEvent, stat: StatConfig, isBest: boolean): void => {
		if (stat.type === StatType.SUCCESS_RATE || stat.size === 0) return;
      
		const includeScrambles = !e.shiftKey;

		let window: Solve[] = [];
		let resultVal: number | null = null;
		const { current, best, bestWindow } = getValues(stat, solves);

		if (isBest) {
			if (!bestWindow) return;
			window = bestWindow;
			resultVal = best;
		} else {
			const history = [...solves]; // Chronological
			if (history.length < stat.size) return;
			window = history.slice(history.length - stat.size);
			resultVal = current;
		}
      
		const header = `Generated by CMOSTimer v${APP_VERSION}\n${getStatLabel(stat, language)}: ${resultVal === DNF_VALUE ? 'DNF' : formatTime(resultVal!, Penalty.NONE, precision)}`;
		const separator = '-'.repeat(16);
		const list = window.map((s, i) => {
			const timeStr = formatTime(s.time, s.penalty, precision);
			if (includeScrambles) {
				// Handle relay scrambles (array of arrays)
				const scrambleStr = s.scramble.map(part => part.join(' ')).join(' | ');
				return `${i + 1}. ${timeStr}   ${scrambleStr}`;
			}
			return `${i + 1}. ${timeStr}`;
		}).join('\n');

		const exportText = `${header}\n${separator}\n${list}`;
		navigator.clipboard.writeText(exportText);
		setCopyFeedback(stat.id + (isBest ? '_best' : '_curr'));
		setTimeout(() => setCopyFeedback(null), 1000);
	};

	const rows = useMemo(() => {
		return config.map(stat => {
			const { current, best } = getValues(stat, solves);
			const isPB = current !== null && best !== null && current === best && current !== DNF_VALUE;
			const fmt = (val: number | null): string => {
				if (val === null) return '-';
				if (val === DNF_VALUE) return 'DNF';
				if (stat.type === StatType.SUCCESS_RATE) return formatPercent(val);
				return formatTime(val, Penalty.NONE, precision);
			};

			let toBeat: number | null | 'IMPOSSIBLE' | 'ANY' = null;
			if (best && best !== DNF_VALUE && stat.type !== StatType.SUCCESS_RATE) 
				toBeat = getRequiredTime(stat, solves, best);
          

			return {
				id: stat.id,
				config: stat,
				label: getStatLabel(stat, language),
				current: fmt(current),
				best: fmt(best),
				toBeat,
				isPB
			};
		});
	}, [config, solves, precision]);

	return (
		<div className="flex flex-col bg-zinc-900/80 backdrop-blur-sm rounded-lg border border-zinc-800 p-2 shadow-lg min-w-[240px]">
			<div className="grid grid-cols-[1.2fr_1fr_1fr_1fr] gap-x-2 gap-y-1 text-xs mb-1 pb-1 border-b border-zinc-800 font-bold text-zinc-500 uppercase tracking-wider">
				<div>Stat</div>
				<div className="text-right">Cur</div>
				<div className="text-right">Best</div>
				<div className="text-right" title="Time needed on next solve to beat PB">Next</div>
			</div>
			{rows.map(row => (
				<div 
					key={row.id} 
					className="grid grid-cols-[1.2fr_1fr_1fr_1fr] gap-x-2 gap-y-1 text-sm rounded px-1 relative group"
				>
					<div className="font-bold text-zinc-400 text-xs pt-0.5 truncate">{row.label}</div>
                
					{/* Current Value Column */}
					<div 
						onClick={(e) => handleExport(e, row.config, false)}
						className={`text-right font-mono cursor-pointer hover:bg-zinc-800 rounded px-1 relative truncate ${
							row.isPB && pbVisuals !== PBVisualType.NONE ? getThemeTextColorClass(theme) + ' font-bold' : 
								row.current === '-' ? 'text-zinc-600' : 
									row.current === 'DNF' ? 'text-red-400' : 'text-zinc-100'
						}`}
						title="Copy current details (Shift+Click for times only)"
					>
						{copyFeedback === row.id + '_curr' && <span className="absolute inset-0 bg-green-500 text-zinc-950 text-[10px] flex items-center justify-center rounded">{t('data.copied.short', language || Language.EN)}</span>}
						{row.current}
					</div>

					{/* Best Value Column */}
					<div 
						onClick={(e) => handleExport(e, row.config, true)}
						className={`text-right font-mono cursor-pointer hover:bg-zinc-800 rounded px-1 relative truncate ${row.best === '-' ? 'text-zinc-700' : row.best === 'DNF' ? 'text-red-900' : 'text-zinc-400'}`}
						title="Copy best details (Shift+Click for times only)"
					>
						{copyFeedback === row.id + '_best' && <span className="absolute inset-0 bg-green-500 text-zinc-950 text-[10px] flex items-center justify-center rounded">{t('data.copied.short', language || Language.EN)}</span>}
						{row.best}
					</div>

					{/* To Beat Column */}
					<div className="text-right font-mono text-zinc-500 text-xs pt-0.5 truncate">
						{row.toBeat === 'IMPOSSIBLE' ? '-' : 
							row.toBeat === 'ANY' ? 'Any' :
								row.toBeat === null ? '' : 
									formatTime(row.toBeat as number, Penalty.NONE, precision)}
					</div>
				</div>
			))}
		</div>
	);
};

export default StatsPanel;


