[package]
name = "cmostimer"
version = "3.0.1"
description = "CMOSTimer desktop app"
authors = ["CMOSTimer"]
edition = "2021"

[package.metadata.tauri]

[lib]
name = "cmostimer_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-store = "2"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
