import { APP_VERSION } from './constants';

export const getGeneratedByHeader = (): string =>
	`Generated by CMOSTimer v${APP_VERSION}`;

export const getSolveExportBanner = (): string =>
	`---------- Export by CMOSTimer v${APP_VERSION} ----------`;
