import { Penalty, Session, Solve, SolveMap, TimePrecision } from '../types';
import { formatDate } from './date';
import { formatTime } from './formatting';
import { getSolveTime } from './math';

const escapeHtml = (value: string): string => value
	.replaceAll('&', '&amp;')
	.replaceAll('<', '&lt;')
	.replaceAll('>', '&gt;')
	.replaceAll('"', '&quot;')
	.replaceAll("'", '&#039;');

const getSessionSolves = (session: Session, solves: SolveMap): Solve[] => session.solveIds
	.map(id => solves[id])
	.filter((solve): solve is Solve => !!solve)
	.sort((left, right) => left.timestamp - right.timestamp);

/** A self-contained HTML document suitable for the browser print dialog. */
export const buildPrintableSessionReport = (session: Session, solves: SolveMap, precision: TimePrecision): string => {
	const sessionSolves = getSessionSolves(session, solves);
	const completedTimes = sessionSolves.map(getSolveTime).filter((time): time is number => time !== null);
	const best = completedTimes.length > 0 ? Math.min(...completedTimes) : null;
	const mean = completedTimes.length > 0 ? completedTimes.reduce((sum, time) => sum + time, 0) / completedTimes.length : null;
	const dnfCount = sessionSolves.filter(solve => solve.penalty === Penalty.DNF || solve.penalty === Penalty.DNS).length;
	const rows = sessionSolves.map((solve, index) => `
		<tr>
			<td>${index + 1}</td>
			<td>${escapeHtml(formatDate(solve.timestamp))}</td>
			<td class="time">${escapeHtml(formatTime(solve.time, solve.penalty, precision))}</td>
			<td>${escapeHtml(solve.scramble.map(part => part.join(' ')).join(' | '))}</td>
			<td>${escapeHtml((solve.tags || []).join(', '))}</td>
			<td>${escapeHtml(solve.comment || '')}</td>
		</tr>`).join('');

	return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>${escapeHtml(session.name)} — CMOSTimer Session Report</title>
<style>
	@page { size: auto; margin: 14mm; }
	* { box-sizing: border-box; }
	body { color: #18181b; font: 11px/1.4 Arial, sans-serif; margin: 0; }
	h1 { font-size: 22px; margin: 0 0 3px; }
	.subtitle { color: #52525b; margin: 0 0 18px; }
	.summary { display: grid; grid-template-columns: repeat(4, 1fr); border: 1px solid #d4d4d8; border-radius: 6px; margin-bottom: 18px; overflow: hidden; }
	.summary div { border-right: 1px solid #d4d4d8; padding: 9px 12px; }
	.summary div:last-child { border-right: 0; }
	.label { color: #71717a; display: block; font-size: 9px; font-weight: bold; letter-spacing: .06em; text-transform: uppercase; }
	.value { font-family: ui-monospace, SFMono-Regular, Consolas, monospace; font-size: 15px; font-weight: bold; }
	table { border-collapse: collapse; table-layout: fixed; width: 100%; }
	th { background: #f4f4f5; color: #52525b; font-size: 9px; letter-spacing: .04em; text-align: left; text-transform: uppercase; }
	th, td { border: 1px solid #d4d4d8; overflow-wrap: anywhere; padding: 6px; vertical-align: top; }
	th:nth-child(1), td:nth-child(1) { width: 5%; text-align: right; }
	th:nth-child(2), td:nth-child(2) { width: 11%; }
	th:nth-child(3), td:nth-child(3) { width: 11%; }
	th:nth-child(4), td:nth-child(4) { width: 42%; font-family: ui-monospace, SFMono-Regular, Consolas, monospace; }
	th:nth-child(5), td:nth-child(5) { width: 13%; }
	th:nth-child(6), td:nth-child(6) { width: 18%; }
	.time { font-family: ui-monospace, SFMono-Regular, Consolas, monospace; font-weight: bold; white-space: nowrap; }
	footer { color: #71717a; font-size: 9px; margin-top: 12px; }
	@media print { tr { break-inside: avoid; } }
</style>
</head>
<body>
	<h1>${escapeHtml(session.name)}</h1>
	<p class="subtitle">CMOSTimer Session Report · Generated ${escapeHtml(new Date().toLocaleString())}</p>
	<section class="summary">
		<div><span class="label">Solves</span><span class="value">${sessionSolves.length}</span></div>
		<div><span class="label">Best</span><span class="value">${best === null ? '—' : escapeHtml(formatTime(best, Penalty.NONE, precision))}</span></div>
		<div><span class="label">Mean finished</span><span class="value">${mean === null ? '—' : escapeHtml(formatTime(mean, Penalty.NONE, precision))}</span></div>
		<div><span class="label">DNF / DNS</span><span class="value">${dnfCount}</span></div>
	</section>
	<table>
		<thead><tr><th>#</th><th>Date</th><th>Time</th><th>Scramble</th><th>Tags</th><th>Comment</th></tr></thead>
		<tbody>${rows}</tbody>
	</table>
	<footer>Generated by CMOSTimer</footer>
</body>
</html>`;
};
